name: bcbs_connector
version: '1.0.0'
config-version: 2

profile: default

flags:
  require_ref_searches_node_package_before_root: true

vars:
  exclude_packages: ["all"]
  claims_enabled: true
  hcc_recapture_year_lookback: 2
  tuva_schema_prefix: bcbs

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

seeds:
  bcbs_connector:
    +schema: input_layer
