-- Staging model for BCBS medical claims
-- Pulls raw columns from commercial_medical_claims with type casts only
-- Renaming and null placeholders are handled in the intermediate layer

select
    cast(claim_id as {{ dbt.type_string() }}) as int_clm_num,
    cast(claim_line_id as {{ dbt.type_int() }}) as clm_line_num,
    cast(parse_json(data):revenue_code as {{ dbt.type_string() }}) as revenue_cd,
    cast(parse_json(data):place_of_service as {{ dbt.type_string() }}) as cms_place_srv_cd,
    cast(parse_json(data):subscriber_id as {{ dbt.type_string() }}) as cursubid,
    cast(parse_json(data):mbi_number as {{ dbt.type_string() }}) as bcmbrnbr,
    cast('BCBS' as string) as payer,
    null as market,
    cast(parse_json(data):line_of_business as string) as lob,
    cast(parse_json(data):date_of_service_to as date) as svcdt,
    cast(parse_json(data):inpatient_admit_date as date) as admitdt,
    cast(parse_json(data):inpatient_discharge_date as date) as dischdt,
    cast(parse_json(data):source_system_code as {{ dbt.type_string() }}) as admit_source_cd,
    cast(parse_json(data):type_of_admission as {{ dbt.type_string() }}) as type_admit_cd,
    cast(parse_json(data):patient_discharge_status as {{ dbt.type_string() }}) as disch_stat_cd,
    cast(parse_json(data):bill_type as {{ dbt.type_string() }}) as bill_type_cd,
    cast(parse_json(data):processed_drg_code as {{ dbt.type_string() }}) as drg_cd,
    cast(parse_json(data):units_of_service as {{ dbt.type_string() }}) as srv_units,
    cast(null as {{ dbt.type_string() }}) as dw_srv_units,
    cast(parse_json(data):procedure_code as {{ dbt.type_string() }}) as hcpcs_proc_cd,
    cast(parse_json(data):procedure_code as {{ dbt.type_string() }}) as cpt_proc_cd,
    cast(parse_json(data):adjustment_code as {{ dbt.type_string() }}) as cpt_pmod1_cd,
    cast(null as {{ dbt.type_string() }}) as cpt_pmod2_cd,
    cast(null as {{ dbt.type_string() }}) as cpt_pmod3_cd,
    cast(parse_json(data):rendering_provider_npi as {{ dbt.type_string() }}) as sprovnpi,
    cast(parse_json(data):billing_provider_npi as {{ dbt.type_string() }}) as bprovnpi,
    cast(parse_json(data):paid_date as date) as pddate,
    cast(null as {{ dbt.type_string() }}) as charge_amt,
    cast(null as {{ dbt.type_string() }}) as netpay,
    cast(parse_json(data):paid_amount as {{ dbt.type_string() }}) as paid,
    cast(null as {{ dbt.type_string() }}) as coins_amt,
    cast(parse_json(data):copay_amount as {{ dbt.type_string() }}) as copay_amt,
    cast(parse_json(data):deductible_amount as {{ dbt.type_string() }}) as deduct_amt,
    cast(null as {{ dbt.type_string() }}) as dw_mem_liab_amt,
    cast(parse_json(data):cob_amount as {{ dbt.type_string() }}) as cobamt,
    cast(10 as {{ dbt.type_string() }}) as icd_subm_ind,
    cast(parse_json(data):icd_diagnoses_1 as {{ dbt.type_string() }}) as icd_diag1_cd,
    cast(parse_json(data):icd_diagnoses_2 as {{ dbt.type_string() }}) as icd_diag2_cd,
    cast(parse_json(data):icd_diagnoses_3 as {{ dbt.type_string() }}) as icd_diag3_cd,
    cast(parse_json(data):icd_diagnoses_4 as {{ dbt.type_string() }}) as icd_diag4_cd,
    cast(parse_json(data):icd_diagnoses_5 as {{ dbt.type_string() }}) as icd_diag5_cd,
    cast(parse_json(data):icd_diagnoses_6 as {{ dbt.type_string() }}) as icd_diag6_cd,
    cast(parse_json(data):icd_diagnoses_7 as {{ dbt.type_string() }}) as icd_diag7_cd,
    cast(parse_json(data):icd_diagnoses_8 as {{ dbt.type_string() }}) as icd_diag8_cd,
    cast(parse_json(data):icd_diagnoses_9 as {{ dbt.type_string() }}) as icd_diag9_cd,
    cast(parse_json(data):icd_diagnoses_10 as {{ dbt.type_string() }}) as icd_diag10_cd,
    cast(parse_json(data):icd_procedure_1 as {{ dbt.type_string() }}) as icd_proc1_cd,
    cast(parse_json(data):icd_procedure_2 as {{ dbt.type_string() }}) as icd_proc2_cd,
    cast(parse_json(data):icd_procedure_3 as {{ dbt.type_string() }}) as icd_proc3_cd,
    cast(parse_json(data):icd_procedure_4 as {{ dbt.type_string() }}) as icd_proc4_cd,
    cast(parse_json(data):icd_procedure_5 as {{ dbt.type_string() }}) as icd_proc5_cd,
    cast(null as {{ dbt.type_string() }}) as dw_netwk_ind,
    cast(null as {{ dbt.type_string() }}) as curr_clm_ind,
    cast(parse_json(data):incurred_date as date) as date_id,
    current_timestamp as _run_time,
    null as s3_path,
    file_group_id as filename
from {{ source('bcbs', 'bcbsm_med_claim') }}
