-- Staging model for BCBS medical claims
-- Pulls raw columns from commercial_medical_claims with type casts only
-- Renaming and null placeholders are handled in the intermediate layer

select
    cast(int_clm_num as {{ dbt.type_string() }}) as int_clm_num,
    cast(clm_line_num as {{ dbt.type_int() }}) as clm_line_num,
    cast(revenue_cd as {{ dbt.type_string() }}) as revenue_cd,
    cast(cms_place_srv_cd as {{ dbt.type_string() }}) as cms_place_srv_cd,
    cast(cursubid as {{ dbt.type_string() }}) as cursubid,
    cast(bcmbrnbr as {{ dbt.type_string() }}) as bcmbrnbr,
    payer,
    market,
    lob,
    cast(svcdt as date) as svcdt,
    cast(admitdt as date) as admitdt,
    cast(dischdt as date) as dischdt,
    cast(admit_source_cd as {{ dbt.type_string() }}) as admit_source_cd,
    cast(type_admit_cd as {{ dbt.type_string() }}) as type_admit_cd,
    cast(disch_stat_cd as {{ dbt.type_string() }}) as disch_stat_cd,
    cast(bill_type_cd as {{ dbt.type_string() }}) as bill_type_cd,
    cast(drg_cd as {{ dbt.type_string() }}) as drg_cd,
    cast(srv_units as {{ dbt.type_string() }}) as srv_units,
    cast(dw_srv_units as {{ dbt.type_string() }}) as dw_srv_units,
    cast(hcpcs_proc_cd as {{ dbt.type_string() }}) as hcpcs_proc_cd,
    cast(cpt_proc_cd as {{ dbt.type_string() }}) as cpt_proc_cd,
    cast(cpt_pmod1_cd as {{ dbt.type_string() }}) as cpt_pmod1_cd,
    cast(cpt_pmod2_cd as {{ dbt.type_string() }}) as cpt_pmod2_cd,
    cast(cpt_pmod3_cd as {{ dbt.type_string() }}) as cpt_pmod3_cd,
    cast(sprovnpi as {{ dbt.type_string() }}) as sprovnpi,
    cast(bprovnpi as {{ dbt.type_string() }}) as bprovnpi,
    cast(pddate as date) as pddate,
    cast(charge_amt as {{ dbt.type_string() }}) as charge_amt,
    cast(netpay as {{ dbt.type_string() }}) as netpay,
    cast(paid as {{ dbt.type_string() }}) as paid,
    cast(coins_amt as {{ dbt.type_string() }}) as coins_amt,
    cast(copay_amt as {{ dbt.type_string() }}) as copay_amt,
    cast(deduct_amt as {{ dbt.type_string() }}) as deduct_amt,
    cast(dw_mem_liab_amt as {{ dbt.type_string() }}) as dw_mem_liab_amt,
    cast(cobamt as {{ dbt.type_string() }}) as cobamt,
    cast(icd_subm_ind as {{ dbt.type_string() }}) as icd_subm_ind,
    cast(icd_diag1_cd as {{ dbt.type_string() }}) as icd_diag1_cd,
    cast(icd_diag2_cd as {{ dbt.type_string() }}) as icd_diag2_cd,
    cast(icd_diag3_cd as {{ dbt.type_string() }}) as icd_diag3_cd,
    cast(icd_diag4_cd as {{ dbt.type_string() }}) as icd_diag4_cd,
    cast(icd_diag5_cd as {{ dbt.type_string() }}) as icd_diag5_cd,
    cast(icd_diag6_cd as {{ dbt.type_string() }}) as icd_diag6_cd,
    cast(icd_diag7_cd as {{ dbt.type_string() }}) as icd_diag7_cd,
    cast(icd_diag8_cd as {{ dbt.type_string() }}) as icd_diag8_cd,
    cast(icd_diag9_cd as {{ dbt.type_string() }}) as icd_diag9_cd,
    cast(icd_diag10_cd as {{ dbt.type_string() }}) as icd_diag10_cd,
    cast(icd_proc1_cd as {{ dbt.type_string() }}) as icd_proc1_cd,
    cast(icd_proc2_cd as {{ dbt.type_string() }}) as icd_proc2_cd,
    cast(icd_proc3_cd as {{ dbt.type_string() }}) as icd_proc3_cd,
    cast(icd_proc4_cd as {{ dbt.type_string() }}) as icd_proc4_cd,
    cast(icd_proc5_cd as {{ dbt.type_string() }}) as icd_proc5_cd,
    cast(dw_netwk_ind as {{ dbt.type_string() }}) as dw_netwk_ind,
    cast(curr_clm_ind as {{ dbt.type_string() }}) as curr_clm_ind,
    cast(date_id as date) as date_id,
    _run_time,
    s3_path,
    filename
from {{ source('bcbs', 'commercial_medical_claims') }}
