select
    person_id,
    member_id,
    subscriber_id,
    gender,
    race,
    birth_date,
    death_date,
    death_flag,
    enrollment_start_date,
    enrollment_end_date,
    payer,
    payer_type,
    plan,
    original_reason_entitlement_code,
    dual_status_code,
    medicare_status_code,
    group_id,
    group_name,
    name_suffix,
    first_name,
    middle_name,
    last_name,
    email,
    ethnicity,
    social_security_number,
    subscriber_relation,
    enrollment_status,
    hospice_flag,
    institutional_snp_flag,
    long_term_institutional_flag,
    address,
    city,
    state,
    zip_code,
    phone,
    data_source,
    file_name,
    file_date,
    ingest_datetime,
    x_program_type,
    x_market,
    x_mem_mth_cnt
from {{ ref('int_bcbs_member_eligibility') }}
where person_id is not null
  and member_id is not null
  and x_mem_mth_cnt = 1
