select
    person_id,
    patient_id,
    member_id,
    payer,
    plan,
    data_source,
    payer_attributed_provider,
    payer_attributed_provider_practice,
    payer_attributed_provider_organization,
    payer_attributed_provider_lob,
    custom_attributed_provider,
    custom_attributed_provider_practice,
    custom_attributed_provider_organization,
    custom_attributed_provider_lob,
    member_effective_date,
    member_term_date,
    year_month,
    file_name,
    file_date,
    ingest_datetime,
    x_provider_specialty,
    x_program_type,
    x_market
from {{ ref('int_bcbs_provider_attribution') }}
where person_id is not null
